---

- hosts: localhost

  tasks:

    - name: "Deploy gitconfig"
      template:
        src: gitconfig
        dest: ~/.gitconfig
      tags: git

    - name: "Create directory ~/.config"
      file:
        path: ~/.config
        state: directory

    - name: "Deploy fish config"
      template:
        src: config.fish
        dest: ~/.config/fish/config.fish
      tags: fish

    - name: "Install fisher"
      command: curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
      args:
        creates: ~/.config/fish/functions/fisher.fish
      tags: fish

    - name: "Setup starship config"
      template:
        src: starship.toml
        dest: ~/.config/starship.toml
      tags:
        - starship
        - fish
