---

- hosts: localhost

  tasks:
  
    - name: "Check if {{ item }} is installed"
      command: 'which {{ item }}'
      register: has_installed
      failed_when: False
      changed_when: False
      check_mode: no
      with_items:
        - vim
        - tmux
        - git
        - fish
      check_mode: false
      tags: always
    
    - debug: 
        var: has_installed.results
        verbosity: 2

    - name: "Deploy vimrc"
      template:
        src: .vimrc
        dest: ~/.vimrc
      when: has_installed.results[0].rc == 0
      tags: vim

    - name: "Setup vundle"
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
      tags: vim
    
    - name: "Install vundle plugins"
      shell: "vim +PluginInstall +qall"
      tags: vim

    - name: "Deploy tmux.conf"
      template:
        src: .tmux.conf
        dest: ~/.tmux.conf
      when: has_installed.results[1].rc == 0
      tags: tmux

    - name: "Deploy gitconfig"
      template:
        src: gitconfig
        dest: ~/.gitconfig
      when: has_installed.results[2].rc == 0
      tags: git

    - name: "Deploy fish config"
      template:
        src: config.fish
        dest: ~/.config/fish/config.fish
      when: has_installed.results[3].rc == 0
      tags: fish
