---

- hosts: localhost

  tasks:
    - name: "Install homebrew"
      shell: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      args:
        creates: /usr/local/bin/brew

    - name: "Get installed brew packages"
      command: "brew list"
      register: brew_packages
      check_mode: no
      tags:
        - brew_packages

    - debug:
        var: brew_packages
        verbosity: 2
      tags:
        - brew_packages

    - name: "Install brew packages"
      command: "brew install {{ item }}"
      with_lines: cat brew_list.txt
      when:
        - item not in brew_packages.stdout_lines
      tags:
        - brew_packages

    - name: "Install brew casks"
      command: "brew cask install {{ item }}"
      with_lines: cat brew_cask_list.txt

    - name: "Install apps from app store"
      command: "mas install {{ item }}"
      with_lines: cat appstore_apps.txt
      tags:
        - app_store

- name: Run deploy play
  import_playbook: deploy.yml
