---

- hosts: localhost

  tasks:
    - name: "Install brew packages"
      homebrew:
        state: present
        name: "{{ query('lines', 'cat brew_list.txt') }}"
      tags:
        - brew_packages

    - name: "Install apps from app store"
      command: "mas install {{ item }}"
      with_lines: cat appstore_apps.txt
      tags:
        - app_store

- name: Run deploy play
  import_playbook: deploy.yml
